"""Permission and role definitions. Authorization is permission-based, never role-name based."""

ORG_PERMISSIONS = [
    "org.view",
    "org.manage",
    "users.view",
    "users.create",
    "users.manage",
    "users.delete",
    "roles.view",
    "roles.manage",
    "devices.view",
    "devices.create",
    "devices.edit",
    "devices.delete",
    "devices.import",
    "devices.export",
    "devices.ping",
    "groups.view",
    "groups.manage",
    "checks.view",
    "checks.manage",
    "checks.run",
    "monitoring.view",
    "monitoring.run",
    "alerts.view",
    "alerts.manage",
    "alerts.acknowledge",
    "reports.view",
    "reports.export",
    "ai.view",
    "ai.ask",
    "notifications.manage",
    "api_keys.manage",
    "audit.view",
    "billing.view",
    "billing.manage",
    "settings.manage",
]

PLATFORM_PERMISSIONS = [
    "platform.view",
    "platform.manage_orgs",
    "platform.manage_plans",
    "platform.manage_subscriptions",
    "platform.view_analytics",
    "platform.manage_system",
    "platform.view_audit",
]

ROLES = {
    "org_owner": {
        "description": "Full control over the organization, users, billing and settings.",
        "permissions": list(ORG_PERMISSIONS),
        "scope": "organization",
    },
    "org_admin": {
        "description": "Manages users, devices, groups, monitoring, alerts and reports.",
        "permissions": [
            "org.view",
            "users.view",
            "users.create",
            "users.manage",
            "users.delete",
            "roles.view",
            "roles.manage",
            "devices.view",
            "devices.create",
            "devices.edit",
            "devices.delete",
            "devices.import",
            "devices.export",
            "devices.ping",
            "groups.view",
            "groups.manage",
            "checks.view",
            "checks.manage",
            "checks.run",
            "monitoring.view",
            "monitoring.run",
            "alerts.view",
            "alerts.manage",
            "alerts.acknowledge",
            "reports.view",
            "reports.export",
            "ai.view",
            "ai.ask",
            "notifications.manage",
            "api_keys.manage",
            "billing.view",
            "audit.view",
            "settings.manage",
        ],
        "scope": "organization",
    },
    "network_manager": {
        "description": "Manages devices, groups, monitoring, alerts and reports.",
        "permissions": [
            "devices.view",
            "devices.create",
            "devices.edit",
            "devices.delete",
            "devices.import",
            "devices.export",
            "devices.ping",
            "groups.view",
            "groups.manage",
            "checks.view",
            "checks.manage",
            "checks.run",
            "monitoring.view",
            "monitoring.run",
            "alerts.view",
            "alerts.manage",
            "alerts.acknowledge",
            "reports.view",
            "reports.export",
            "ai.view",
            "ai.ask",
        ],
        "scope": "organization",
    },
    "network_operator": {
        "description": "Views devices, runs ping checks, views alerts and reports.",
        "permissions": [
            "devices.view",
            "devices.ping",
            "groups.view",
            "checks.view",
            "monitoring.view",
            "monitoring.run",
            "alerts.view",
            "reports.view",
            "ai.view",
            "ai.ask",
        ],
        "scope": "organization",
    },
    "viewer": {
        "description": "Read-only access.",
        "permissions": [
            "org.view",
            "users.view",
            "devices.view",
            "groups.view",
            "checks.view",
            "monitoring.view",
            "alerts.view",
            "reports.view",
            "ai.view",
        ],
        "scope": "organization",
    },
    "platform_admin": {
        "description": "Platform-wide administrator.",
        "permissions": list(PLATFORM_PERMISSIONS),
        "scope": "platform",
    },
}
