"""Model registry. Importing this package populates Base.metadata."""
from models.platform import (
    ApiKey,
    AuditLog,
    EmailVerificationToken,
    Organization,
    PasswordResetToken,
    Permission,
    Plan,
    Role,
    Setting,
    Subscription,
    User,
    UserSession,
    role_permissions,
)
from models.network import (
    AlertConfig,
    AlertLog,
    AlertRule,
    CheckResult,
    Device,
    DeviceCheck,
    DeviceGroup,
    InAppNotification,
)
from models.ai import AIInsight, AIChatMessage, AIUsage

__all__ = [
    "ApiKey",
    "AuditLog",
    "EmailVerificationToken",
    "Organization",
    "PasswordResetToken",
    "Permission",
    "Plan",
    "Role",
    "Setting",
    "Subscription",
    "User",
    "UserSession",
    "role_permissions",
    "AlertConfig",
    "AlertLog",
    "AlertRule",
    "CheckResult",
    "Device",
    "DeviceCheck",
    "DeviceGroup",
    "InAppNotification",
    "AIInsight",
    "AIChatMessage",
    "AIUsage",
]
